language: ruby
rvm:
- 2.2.2
deploy:
  provider: heroku
  api_key:
    secure: Ec3Z+SI2Za+UFGdMGFg5DV5HsBIcNmR7EdFV0FOWSHZIDOsqn6++Rhn/mmeViB9c8ijBOIYq97ve1r/xsB1YAtDTf7Zu8+TKi2gOpj+TQ81asBhwWgHmXCZiJ9o8nl7WGmy5uEx8fZY/KhMxUdA/fgk4Rq+VlpATT+p3cxXCGjrhDQ8TAa/OmGRZ2MstnWg80AF2xnB0E0ASzIxhqAtuHxBuPY8YpbPuIuZr++wAPBscQfouklC2OMMHfk1793GOyMdV5zweGmU3dizKsnHEVPBBQDAXrMT4DfrIZZtiMuQY9ljt39QceDpOKndaoDBxRHLzUuRE/ueMfl4DnkcThQ8JOmGYv+0yLRGipwa+GgiYPvOiy+wqQMUd+qPCjK/8eXAamIzxuBcaelcJkydPyTvM/H2g75Rze0cs4EaIdPX98KrqKMdY1198SAHY9VXlmsOO3XK0Tbp2tRqLNI7Bg67KETgvd10LUYGZke8OkHFjK0wwv+R4Yutf0ILwTSIK8Xi0sedWQD9nrNAtn6zJVuhJrWiMIYRX/NrZ970tI6cAR8NRA7fdlGCibsO4OA+w/eOve2F9JmyrUPra7BAylta0d5aGwJoTn4UgR4YCQzL9mSZw1SSmnvr/AV0efjn7jng2ngHUJCMUHzWthNXx3e1y1vdh+T9FExXfIv9A4pM=
  app: safe-reaches-89463
  on:
    repo: QuentinSimonU/projet
